CREATE TABLE IF NOT EXISTS config (
	cron_seconds INT NOT NULL
);

CREATE TABLE IF NOT EXISTS urls (
	key SERIAL PRIMARY KEY,
	url TEXT NOT NULL UNIQUE,
	platform TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS commands (
	key SERIAL PRIMARY KEY,
	command TEXT NOT NULL UNIQUE,
	frequency INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_called_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);