// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Command struct {
	Key          int64
	Command      string
	Frequency    int64
	CreatedAt    time.Time
	LastCalledAt time.Time
}

type Config struct {
	CronSeconds int64
}

type Url struct {
	Key       int64
	Url       string
	Platform  string
	CreatedAt time.Time
}
