// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteCommand(ctx context.Context, command string) (Command, error)
	DeleteUrl(ctx context.Context, url string) (Url, error)
	GetAllCommands(ctx context.Context) ([]Command, error)
	GetAllUrls(ctx context.Context) ([]Url, error)
	GetCommandsByPlatform(ctx context.Context, platform string) (Url, error)
	GetCroneSeconds(ctx context.Context) (int64, error)
	GetTopCommands(ctx context.Context) ([]Command, error)
	InsertUrl(ctx context.Context, arg InsertUrlParams) (Url, error)
	QueryCommands(ctx context.Context, dollar_1 sql.NullString) ([]Command, error)
	UpsertCommand(ctx context.Context, arg UpsertCommandParams) (Command, error)
	UpsertConfig(ctx context.Context, cronSeconds int64) (int64, error)
}

var _ Querier = (*Queries)(nil)
